Fix error message for forbidden error
increments/qiita-cli pull request #149
Opened 2024-06-07 03:01 UTC by wataru86

## What

- API が Forbidden を返した際のエラーメッセージを修正しました。

| before | after |
| --- | --- |
| ![image](https://github.com/increments/qiita-cli/assets/34445284/8a3e7a60-7720-4749-aefb-8a9e8ee0ceb2) | ![image](https://github.com/increments/qiita-cli/assets/34445284/89a94930-5be4-4f78-bf8d-640558ae80f3) |

## Why

- 記事ファイルに不備がある場合に API が Forbidden を返す可能性があるため。
    - 例
        - private を false から true に変更しようとしたとき
        - タグにスペースが含まれているとき

## Refs

- https://github.com/increments/qiita-discussions/discussions/561

2024-06-10 01:15 UTC, tomoasleep requested changes
> 記事ファイルに不備がある場合に API が Forbidden を返す可能性があるため。
> * 例
>   * private を false から true に変更しようとしたとき
>   * タグにスペースが含まれているとき

この例を見る感じ、クライアント側で対処するのではなく、そもそも API が返す status code が適切ではないのでは？ということを思いました。 ([400](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/400) とかを返すべきなのでは？ということを思いました。)

`src/lib/error-handler.ts` は、名前からして汎用的な処理で、 API のエラーに対して、汎用的なエラーメッセージを返す場所なので、 status code の意味と明らかに異なるメッセージを返すのは避けたいです。

(基本的には API 側で対処してほしいですが、) 一時的にクライアントで対応するにしても、汎用的なエラーメッセージの表示箇所ではなく、 command 単位で、エラーメッセージの表示を変更するなど、具体的な箇所で TODO コメント付きで対応してほしいです。

2024-06-14 02:44 UTC, wataru86 commented
@tomoasleep リマインドです。レビューお願いします 🙏

2024-06-14 02:53 UTC, tomoasleep approved these changes
- API 側の問題はいずれ対応予定
- 先にクライアント側のエラー通知を改善しておきたい

ということで、問題がある API を使用している箇所のみエラーメッセージを変更することにした。LGTM 👍

2024-06-14 02:55 UTC, tomoasleep commented
メモ: xt0rted/block-autosquash-commits-action@v2 でテストがスキップされてるが、 public repo ではスキップは不要だと思う。

2024-06-14 03:19 UTC, merged